==== WARMUP ====
WARM    RUN_TIMEOUT           None                    
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
CWD: /home/tsongpet/MSc-SSE-GI-project/_magpie_work/minisat-hack_1687206032/minisat-hack
CMD: ['run-sh/train_1.sh']
STATUS: TIMEOUT
RETURN_CODE: -9
RUNTIME: 30.180254459381104
STDOUT:

STDERR:

!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
Magpie stopped because it was unable to run the (unmodified) target software
Self-diagnostic:
The "run_cmd" command took too long to run
--> consider increasing "run_timeout"
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
==== END ====
Reason: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tsongpet/MSc-SSE-GI-project/bin/local_search.py", line 43, in <module>
    protocol.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/bin/protocol.py", line 69, in run
    self.search.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/algo/local_search.py", line 23, in run
    self.warmup()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/base/algorithm.py", line 145, in warmup
    raise RuntimeError('initial solution has failed')
RuntimeError: initial solution has failed
==== WARMUP ====
WARM    RUN_TIMEOUT           None                    
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
CWD: /home/tsongpet/MSc-SSE-GI-project/_magpie_work/minisat-hack_1687206075/minisat-hack
CMD: ['run-sh/train_2.sh']
STATUS: TIMEOUT
RETURN_CODE: -9
RUNTIME: 30.163301467895508
STDOUT:

STDERR:

!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
Magpie stopped because it was unable to run the (unmodified) target software
Self-diagnostic:
The "run_cmd" command took too long to run
--> consider increasing "run_timeout"
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
==== END ====
Reason: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tsongpet/MSc-SSE-GI-project/bin/local_search.py", line 43, in <module>
    protocol.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/bin/protocol.py", line 69, in run
    self.search.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/algo/local_search.py", line 23, in run
    self.warmup()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/base/algorithm.py", line 145, in warmup
    raise RuntimeError('initial solution has failed')
RuntimeError: initial solution has failed
==== WARMUP ====
WARM    RUN_TIMEOUT           None                    
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
CWD: /home/tsongpet/MSc-SSE-GI-project/_magpie_work/minisat-hack_1687206117/minisat-hack
CMD: ['run-sh/train_3.sh']
STATUS: TIMEOUT
RETURN_CODE: -9
RUNTIME: 30.197470903396606
STDOUT:

STDERR:

!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
Magpie stopped because it was unable to run the (unmodified) target software
Self-diagnostic:
The "run_cmd" command took too long to run
--> consider increasing "run_timeout"
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
==== END ====
Reason: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tsongpet/MSc-SSE-GI-project/bin/local_search.py", line 43, in <module>
    protocol.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/bin/protocol.py", line 69, in run
    self.search.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/algo/local_search.py", line 23, in run
    self.warmup()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/base/algorithm.py", line 145, in warmup
    raise RuntimeError('initial solution has failed')
RuntimeError: initial solution has failed
==== WARMUP ====
WARM    RUN_TIMEOUT           None                    
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
CWD: /home/tsongpet/MSc-SSE-GI-project/_magpie_work/minisat-hack_1687206158/minisat-hack
CMD: ['run-sh/train_4.sh']
STATUS: TIMEOUT
RETURN_CODE: -9
RUNTIME: 30.2042236328125
STDOUT:

STDERR:

!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
Magpie stopped because it was unable to run the (unmodified) target software
Self-diagnostic:
The "run_cmd" command took too long to run
--> consider increasing "run_timeout"
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
==== END ====
Reason: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tsongpet/MSc-SSE-GI-project/bin/local_search.py", line 43, in <module>
    protocol.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/bin/protocol.py", line 69, in run
    self.search.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/algo/local_search.py", line 23, in run
    self.warmup()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/base/algorithm.py", line 145, in warmup
    raise RuntimeError('initial solution has failed')
RuntimeError: initial solution has failed
==== WARMUP ====
WARM    RUN_TIMEOUT           None                    
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
CWD: /home/tsongpet/MSc-SSE-GI-project/_magpie_work/minisat-hack_1687206199/minisat-hack
CMD: ['run-sh/train_5.sh']
STATUS: TIMEOUT
RETURN_CODE: -9
RUNTIME: 30.148694038391113
STDOUT:

STDERR:

!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
Magpie stopped because it was unable to run the (unmodified) target software
Self-diagnostic:
The "run_cmd" command took too long to run
--> consider increasing "run_timeout"
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
==== END ====
Reason: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tsongpet/MSc-SSE-GI-project/bin/local_search.py", line 43, in <module>
    protocol.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/bin/protocol.py", line 69, in run
    self.search.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/algo/local_search.py", line 23, in run
    self.warmup()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/base/algorithm.py", line 145, in warmup
    raise RuntimeError('initial solution has failed')
RuntimeError: initial solution has failed
==== WARMUP ====
WARM    RUN_TIMEOUT           None                    
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
CWD: /home/tsongpet/MSc-SSE-GI-project/_magpie_work/minisat-hack_1687206239/minisat-hack
CMD: ['run-sh/train_6.sh']
STATUS: TIMEOUT
RETURN_CODE: -9
RUNTIME: 30.07992458343506
STDOUT:

STDERR:

!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
Magpie stopped because it was unable to run the (unmodified) target software
Self-diagnostic:
The "run_cmd" command took too long to run
--> consider increasing "run_timeout"
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
==== END ====
Reason: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tsongpet/MSc-SSE-GI-project/bin/local_search.py", line 43, in <module>
    protocol.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/bin/protocol.py", line 69, in run
    self.search.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/algo/local_search.py", line 23, in run
    self.warmup()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/base/algorithm.py", line 145, in warmup
    raise RuntimeError('initial solution has failed')
RuntimeError: initial solution has failed
==== WARMUP ====
WARM    RUN_TIMEOUT           None                    
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
CWD: /home/tsongpet/MSc-SSE-GI-project/_magpie_work/minisat-hack_1687206277/minisat-hack
CMD: ['run-sh/train_7.sh']
STATUS: TIMEOUT
RETURN_CODE: -9
RUNTIME: 30.096713066101074
STDOUT:

STDERR:

!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
Magpie stopped because it was unable to run the (unmodified) target software
Self-diagnostic:
The "run_cmd" command took too long to run
--> consider increasing "run_timeout"
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
==== END ====
Reason: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tsongpet/MSc-SSE-GI-project/bin/local_search.py", line 43, in <module>
    protocol.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/bin/protocol.py", line 69, in run
    self.search.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/algo/local_search.py", line 23, in run
    self.warmup()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/base/algorithm.py", line 145, in warmup
    raise RuntimeError('initial solution has failed')
RuntimeError: initial solution has failed
==== WARMUP ====
WARM    RUN_TIMEOUT           None                    
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
CWD: /home/tsongpet/MSc-SSE-GI-project/_magpie_work/minisat-hack_1687206314/minisat-hack
CMD: ['run-sh/train_8.sh']
STATUS: TIMEOUT
RETURN_CODE: -9
RUNTIME: 30.107347011566162
STDOUT:

STDERR:

!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
Magpie stopped because it was unable to run the (unmodified) target software
Self-diagnostic:
The "run_cmd" command took too long to run
--> consider increasing "run_timeout"
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
==== END ====
Reason: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tsongpet/MSc-SSE-GI-project/bin/local_search.py", line 43, in <module>
    protocol.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/bin/protocol.py", line 69, in run
    self.search.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/algo/local_search.py", line 23, in run
    self.warmup()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/base/algorithm.py", line 145, in warmup
    raise RuntimeError('initial solution has failed')
RuntimeError: initial solution has failed
==== WARMUP ====
WARM    RUN_CODE_ERROR        None                    
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
CWD: /home/tsongpet/MSc-SSE-GI-project/_magpie_work/minisat-hack_1687206351/minisat-hack
CMD: ['run-sh/train_9.sh']
STATUS: SUCCESS
RETURN_CODE: 255
RUNTIME: 0.01959705352783203
STDOUT:
FAILED ON FILE: ../../../data/circuit_fuzz/fuzz_100_19666.cnf
GOT: 127
EXPECTED: 10

STDERR:
run-sh/train_9.sh: line 8: ./simp/minminisat_HACK_999ED_CSSCisat: No such file or directory

!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
Magpie stopped because it was unable to run the (unmodified) target software
Self-diagnostic:
The "run_cmd" command failed with a nonzero exit code
--> try to run it manually
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
==== END ====
Reason: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tsongpet/MSc-SSE-GI-project/bin/local_search.py", line 43, in <module>
    protocol.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/bin/protocol.py", line 69, in run
    self.search.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/algo/local_search.py", line 23, in run
    self.warmup()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/base/algorithm.py", line 145, in warmup
    raise RuntimeError('initial solution has failed')
RuntimeError: initial solution has failed
==== WARMUP ====
WARM    RUN_TIMEOUT           None                    
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
CWD: /home/tsongpet/MSc-SSE-GI-project/_magpie_work/minisat-hack_1687206358/minisat-hack
CMD: ['run-sh/train_10.sh']
STATUS: TIMEOUT
RETURN_CODE: -9
RUNTIME: 30.10110878944397
STDOUT:

STDERR:

!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
Magpie stopped because it was unable to run the (unmodified) target software
Self-diagnostic:
The "run_cmd" command took too long to run
--> consider increasing "run_timeout"
!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*!*
==== END ====
Reason: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tsongpet/MSc-SSE-GI-project/bin/local_search.py", line 43, in <module>
    protocol.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/bin/protocol.py", line 69, in run
    self.search.run()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/algo/local_search.py", line 23, in run
    self.warmup()
  File "/home/tsongpet/MSc-SSE-GI-project/magpie/base/algorithm.py", line 145, in warmup
    raise RuntimeError('initial solution has failed')
RuntimeError: initial solution has failed
